site_name: Django Rubble Docs
repo_url: https://github.com/WoosterTech/django-rubble

theme:
  name: "material"

plugins:
  - include-markdown
  - search
  # - gen-files:
  #     scripts:
  #     - scripts/gen_ref_pages.py
  # - literate-nav:
  #     nav_file: SUMMARY.md
  # - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            extensions:
              - griffe_fieldz

nav:
  - Home: index.md
  - Code Reference:
    - Checks:
      - checks/errors.md
      - checks/messages.md
    - Fields:
      - Django: fields/db_fields.md
    - Models:
      - models/number_models.md
    - Utilities:
      - utils/default_funcs.md
      - utils/enums.md
      - utils/model_helpers.md
      - utils/numbers.md
  - Contributing: contributing.md
  - Changelog: changelog.md

extra:
  social:
    - icon: material/web
      link: "https://woostertech.com"
      name: WoosterTech
    - icon: material/github
      link: "https://github.com/WoosterTech//django-rubble"
      name: GitHub
    - icon: material/email
      link: "mailto:karl@woostertech.com"