

from collections.abc import Sequence
from typing import Any

from django.contrib import admin
from django.db.models import QuerySet

from .manager import HistoryManager
from .models import HistoricalChanges
from .template_utils import HistoricalRecordContextHelper

SIMPLE_HISTORY_EDIT = ...
class SimpleHistoryAdmin(admin.ModelAdmin):
    history_list_display = ...
    object_history_template = ...
    object_history_list_template = ...
    object_history_form_template = ...
    history_list_per_page = ...
    def get_urls(self): # -> list[URLResolver | URLPattern]:
        ...

    def history_view(self, request, object_id, extra_context=...): # -> HttpResponse:
        ...

    def get_history_queryset(self, request, history_manager: HistoryManager, pk_name: str, object_id: Any) -> QuerySet:
        ...

    def get_history_list_display(self, request) -> Sequence[str]:
        ...

    def get_historical_record_context_helper(self, request, historical_record: HistoricalChanges) -> HistoricalRecordContextHelper:
        ...

    def set_history_delta_changes(self, request, historical_records: Sequence[HistoricalChanges], foreign_keys_are_objs=...): # -> None:
        ...

    def history_view_title(self, request, obj): # -> Any:
        ...

    def response_change(self, request, obj): # -> HttpResponseRedirect | TemplateResponse:
        ...

    def history_form_view(self, request, object_id, version_id, extra_context=...): # -> HttpResponseRedirect | TemplateResponse | HttpResponse:
        ...

    def history_form_view_title(self, request, obj): # -> Any:
        ...

    def render_history_view(self, request, template, context, **kwargs): # -> HttpResponse:
        ...

    def save_model(self, request, obj, form, change): # -> None:
        ...

    @property
    def content_type_model_cls(self):
        ...

    def revert_disabled(self, request, obj=...): # -> bool:
        ...

    def has_view_permission(self, request, obj=...):
        ...

    def has_change_permission(self, request, obj=...):
        ...

    def has_view_or_change_permission(self, request, obj=...):
        ...

    def has_view_history_or_change_history_permission(self, request, obj=...):
        ...

    def has_view_history_permission(self, request, obj=...):
        ...

    def has_change_history_permission(self, request, obj=...):
        ...

    @property
    def enforce_history_permissions(self): # -> Any | bool:
        ...



